(ns starkbank.balance
  "The Balance map displays the current balance of the workspace,
  which is the result of the sum of all transactions within this
  workspace. The balance is never generated by the user, but it
  can be retrieved to see the information available.

  ## Attributes (return-only):
    - `:id` [string, default nil]: unique id returned when Balance is created. ex: \"5656565656565656\"
    - `:amount` [integer, default nil]: current balance amount of the workspace in cents. ex: 200 (= R$ 2.00)
    - `:currency` [string, default nil]: currency of the current workspace. Expect others to be added eventually. ex: \"BRL\"
    - `:updated` [string, default nil]: update datetime for the balance. ex: \"2020-03-26T19:32:35.418698+00:00\""
  (:refer-clojure :exclude [get set])
  (:require [starkbank.utils.rest :refer [get-page]]
            [starkbank.settings :refer [credentials]])
  )

(defn- resource []
  "balance")

(defn get
  "Receive the Balance entity linked to your workspace in the Stark Bank API

  ## Options:
    - `:user` [Project or Organization, default nil]: Project or Organization map returned from starkbank.user/project or starkbank.user/organization. Only necessary if starkbank.settings/user has not been set.

  ## Return:
    - Balance map with updated attributes"
  ([] (-> (get-page @credentials (resource) {})
          (:content)
          (first)
          (:amount)))

  ([user] (-> (get-page user (resource) {})
              (:content)
              (first)
              (:amount)))
  )
