(ns starkbank.corporate-balance
  "The CorporateBalance map displays the current corporate balance of the Workspace,
  which is the result of the sum of all transactions within this
  Workspace. The balance is never generated by the user, but it
  can be retrieved to see the available information.

  ## Attributes (return-only):
    - `:id` [string, default nil]: unique id returned when CorporateBalance is created. ex: \"5656565656565656\"
    - `:amount` [integer, default nil]: current balance amount of the Workspace in cents. ex: 200 (= R$ 2.00)
    - `:limit` [integer, default nil]: the maximum negative balance allowed by the user. ex: 10000 (= R$ 100.00)
    - `:max-limit` [integer, default nil]: the maximum negative balance allowed by Stark Bank. ex: 100000 (= R$ 1000.00)
    - `:currency` [string, default nil]: currency of the current Workspace. Expect others to be added eventually. ex: \"BRL\"
    - `:updated` [string, default nil]: latest update datetime for the CorporateBalance. ex: \"2020-03-26T19:32:35.418698+00:00\""
  (:refer-clojure :exclude [get])
  (:require [starkbank.utils.rest :refer [get-stream]]
            [starkbank.settings :refer [credentials]]))

(defn- resource []
  "corporate-balance")

(defn get
  "Receive the CorporateBalance map linked to your Workspace in the Stark Bank API

  ## Options:
    - `:user` [Project or Organization, default nil]: Project or Organization map returned from starkbank.user/project or starkbank.user/organization. Only necessary if starkbank.settings/user has not been set.

  ## Return:
    - CorporateBalance map with updated attributes"
  ([]
   (-> (get-stream @credentials (resource) {})
       (first)))

  ([user]
   (-> (get-stream user (resource) {})
       (first))))
