(ns starkbank.split
  "A Split is a portion of a payment (Invoice or BoletoPayment) that is
  automatically routed to a SplitReceiver when the payment is settled.
  Splits are never created directly through this SDK: they are generated
  by the Stark Bank API itself whenever a receivable carrying SplitReceivers
  is paid. Use `get`, `query` or `page` to read the Splits the API has
  already generated for you.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when split is created. ex: \"5656565656565656\"
    - `:amount` [integer]: value sent to the receiver. ex: 1000 (= R$ 10.00)
    - `:receiver-id` [string]: split receiver unique id. ex: \"5656565656565656\"
    - `:source` [string]: source receivable which generated this split. ex: \"5656565656565656\"
    - `:external-id` [string]: unique id, generated by the system, to avoid duplicated splits. ex: \"invoice/1234/receiver/5678\"
    - `:tags` [list of strings, default nil]: list of strings for tagging
    - `:scheduled` [string, default now]: payment scheduled date or datetime. ex: \"2020-03-10 10:30:00.000000+00:00\"
    - `:status` [string]: current payment status. ex: \"success\", \"failed\", \"canceled\" or \"processing\"
    - `:created` [string]: creation datetime for the payment. ex: \"2020-03-10 10:30:00.000000+00:00\"
    - `:updated` [string]: update datetime for the payment. ex: \"2020-03-10 10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get])
  (:require [starkbank.utils.rest :refer [get-id get-page get-stream]]
            [starkbank.settings :refer [credentials]]))

(defn- resource []
  "split")

(defn get
  "Receive a single Split map previously created in the Stark Bank API by passing its id

  ## Parameters (required):
    - `:id` [string]: map unique id. ex: \"5656565656565656\"

  ## Options:
    - `:user` [Project or Organization, default nil]: Project or Organization map returned from starkbank.user/project or starkbank.user/organization. Only necessary if starkbank.settings/user has not been set.

  ## Return:
    - Split map with updated attributes"
  ([id]
   (-> (get-id @credentials (resource) id {})))

  ([id, user]
   (-> (get-id user (resource) id {}))))

(defn query
  "Receive a stream of Split maps previously created in the Stark Bank API.
  Use this function instead of page if you want to stream the objects without worrying about cursors and pagination.

  ## Options:
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-3-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-3-10\"
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:receiver-ids` [list of strings, default nil]: list of receiver ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:status` [string, default nil]: filter for status of retrieved maps. ex: \"success\", \"failed\", \"canceled\" or \"processing\"
    - `:user` [Project or Organization, default nil]: Project or Organization map returned from starkbank.user/project or starkbank.user/organization. Only necessary if starkbank.settings/user has not been set.

  ## Return:
    - stream of Split maps with updated attributes"
  ([]
   (-> (get-stream @credentials (resource) {})))

  ([params]
   (-> (get-stream @credentials (resource) params)))

  ([params, user]
   (-> (get-stream user (resource) params))))

(defn page
  "Receive a list of up to 100 Split maps previously created in the Stark Bank API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-3-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-3-10\"
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:receiver-ids` [list of strings, default nil]: list of receiver ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:status` [string, default nil]: filter for status of retrieved maps. ex: \"success\", \"failed\", \"canceled\" or \"processing\"
    - `:user` [Project or Organization, default nil]: Project or Organization map returned from starkbank.user/project or starkbank.user/organization. Only necessary if starkbank.settings/user has not been set.

  ## Return:
    - map with :splits and :cursor:
      - `:splits`: list of Split maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page of splits"
  ([]
   (-> (get-page @credentials (resource) {})))

  ([params]
   (-> (get-page @credentials (resource) params)))

  ([params, user]
   (-> (get-page user (resource) params))))
