(ns starkbank.split-test
  "Splits are generated by the Stark Bank API itself whenever an Invoice or
  BoletoPayment carrying SplitReceivers is paid, so there is no 'create'
  function to exercise here: these tests only cover get/query/page."
  (:use [clojure.test])
  (:require [starkbank.split :as split]
            [starkbank.split.log :as log]
            [starkbank.utils.page :as page]
            [starkbank.utils.user :refer [set-project]]))

(set-project)

(deftest query-and-get-splits
  (testing "query and get splits"
    (def splits (take 200 (split/query {:limit 3})))
    (doseq [item splits]
      (is (map? item)))
    (when (seq splits)
      (def split-id (:id (first splits)))
      (is (= split-id (:id (split/get split-id)))))))

(deftest page-splits
  (testing "page splits"
    (def get-page (fn [params] (split/page params)))
    (def ids (page/get-ids get-page 2 {:limit 2}))
    (is (>= 4 (count ids)))))

(deftest query-and-get-split-logs
  (testing "query and get split logs"
    (def logs (take 200 (log/query {:limit 1})))
    (doseq [item logs]
      (is (map? item))
      (is (map? (:split item))))
    (when (seq logs)
      (def split-log (log/get (:id (first logs))))
      (is (not (nil? (:id split-log))))
      ;; :errors so vem preenchido em logs de falha; a API omite quando nao ha erro
      (is (or (nil? (:errors split-log)) (sequential? (:errors split-log))))
      (is (string? (:created split-log)))
      (is (map? (:split split-log))))))

(deftest page-split-logs
  (testing "page split logs"
    (def get-page (fn [params] (log/page params)))
    (def ids (page/get-ids get-page 2 {:limit 2}))
    (is (>= 4 (count ids)))))
